# Generated by Django 4.0.3 on 2022-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(default=None, max_length=255)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('display', models.IntegerField(default=1)),
            ],
        ),
    ]
