# Generated by Django 4.0.3 on 2022-09-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_en',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='date_it',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_it',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
