# Generated by Django 4.0.3 on 2022-09-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_date_en_news_date_it_news_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['title']},
        ),
    ]
