# Generated by Django 3.2.7 on 2021-11-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_it', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('grade_en', models.CharField(max_length=255, null=True)),
                ('grade_it', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=255)),
                ('qualifications', models.CharField(default=None, max_length=255)),
                ('qualifications_en', models.CharField(default=None, max_length=255, null=True)),
                ('qualifications_it', models.CharField(default=None, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_it', models.TextField(null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.role')),
            ],
        ),
    ]
