# Generated by Django 4.0.3 on 2022-09-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20211116_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['role', 'surname', 'name']},
        ),
        migrations.AddField(
            model_name='team',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
