# Generated by Django 4.0.3 on 2022-09-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_role_options_alter_team_options_team_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image2',
        ),
    ]
