# Generated by Django 4.0.3 on 2022-09-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_team_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image2',
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/team'),
        ),
    ]
