# Generated by Django 4.0.3 on 2022-09-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='subservice',
            options={'ordering': ['service', 'order']},
        ),
    ]
