# Generated by Django 3.2.7 on 2021-09-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('favicon', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('icon_footer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmaps_api_key', models.CharField(max_length=255)),
                ('gmaps', models.CharField(max_length=255)),
                ('marker', models.CharField(max_length=255)),
                ('cluster_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
