# Generated by Django 3.2.7 on 2021-10-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211021_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='address_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='closed_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='closed_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='open_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='open_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='error',
            name='error_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='error',
            name='error_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='begin_en',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='begin_it',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_en',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_it',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='partners_en',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='partners_it',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='swiperhomepage',
            name='h1_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='swiperhomepage',
            name='h1_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='swiperhomepage',
            name='h4_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='swiperhomepage',
            name='h4_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typeproject',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typeproject',
            name='name_it',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
