# Generated by Django 4.0.3 on 2022-09-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211022_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lat',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='lng',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
