# Generated by Django 4.0.3 on 2022-09-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_company_lat_company_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sitename',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
