# Generated by Django 4.0.3 on 2022-09-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_company_sitename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='projectgallery',
            options={'ordering': ['project']},
        ),
        migrations.AlterModelOptions(
            name='swiperhomepage',
            options={'ordering': ['h1']},
        ),
        migrations.AlterModelOptions(
            name='typeproject',
            options={'ordering': ['name']},
        ),
    ]
