# Generated by Django 4.0.3 on 2022-09-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_company_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/projects'),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/projectgallery'),
        ),
    ]
