# Generated by Django 4.0.3 on 2022-09-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_project_image_alter_projectgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
