# Generated by Django 4.0.3 on 2022-09-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_project_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_it',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='partners',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='partners_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='partners_it',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
