# Generated by Django 4.0.3 on 2022-09-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_project_end_alter_project_end_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiperhomepage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/swipers'),
        ),
    ]
