# Generated by Django 4.1.3 on 2024-08-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_swiperhomepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_it',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
