# Generated by Django 3.2.7 on 2021-10-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='route_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='route_it',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
